### PR TITLE
Signed, Sealed, Delivered

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Add attribution (source and logo) to downloaded charts and viz from HURUmap-UI.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Peek 2019-11-04 11-51

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DavidLemayian** [comment]
I'm really glad we've been able to move on this pretty quick. Quick questions; How come so much space below chart and the purple background?..

**Comment by karimkawambwa** [comment]
> I'm really glad we've been able to move on this pretty quick. Quick questions; How come so much space below chart and the purple background?..

@DavidLemayian most likely theme setting issue. Its not a problem, in the frontend the theme is set appropriately, i don't think we have bothered with theme setting for our story book.

**Comment by DavidLemayian** [comment]
How hard to fix? I'd say we want anyone looking at our Storybook to get the best experience possible to encourage reuse?

**Comment by karimkawambwa** [comment]
> How hard to fix? I'd say we want anyone looking at our Storybook to get the best experience possible to encourage reuse.

@DavidLemayian doing them configs here should help theme storybook https://github.com/CodeForAfrica/HURUmap-UI/blob/09538f67b9e6e54335ae8b24ee01f941031f404b/stories/Theme.js

**Comment by kilemensi** [comment]
> I'm really glad we've been able to move on this pretty quick. Quick questions; How come so much space below chart and the purple background?..

@DavidLemayian:

1. Spacing: That's just what the story has defined, I'll remove it before merge.
2. Purple: That's the default Material theme _primary_ color.

I've also added a story to track [this and any prime time](https://www.pivotaltracker.com/story/show/169563961) related issues.

cc @karimkawambwa

**Pull request merged**
