### PR TITLE
Show labels default ontop of bar chart and allow tooltip on hover

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Failed to make tooltip eve with mouse so it is fixed on the centre as follows:
Screen Shot 2019-08-28 at 11 50 51 AM

The behaviour on this gif below if not reliable so it is scrapped:

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Looks fine @karimkawambwa ... is it possible to do it without the manual mouse events though?

**Comment by karimkawambwa** [comment]
@kilemensi I don't think there is any other way. 
Without that mouse listener, the tooltip would be stuck at the top.

**Comment by karimkawambwa** [comment]
If anyone wants to take a hack at making this tooltip move with the mouse move please do help. I would be interested to see how. @nerdlet @kilemensi @KhadijaMahanga @DavidLemayian  

For now it will be fixed at the centre of the bar.

**Comment by karimkawambwa** [comment]
Awesome, thanks @kilemensi .
The idea to just make a custom tooltip went over my head.

**Pull request merged**
