### PR TITLE
Add text wrapping to VictoryLabel & Use it for Legend

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

While very capable, `VictoryLabel` doesn't support text wrapping. This PR adds a custom `Label` component built on top of `VictoryLabel` that wraps text _before_ passing it to `VictoryLabel`.

  - [x] Add `Label` component capable of text-wrapping,
  - [x] Update `PieChart` legend to use the `Label` component,
  - [x] Revert the automatic calculation of `PieChart` `origin`, and
  - [x] Arrange components to ensure legend tooltip appears at the very top.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

ezgif com-video-to-gif

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
> 1. You can't just reuse WrapLabel ?

`WrapLabel` bypasses `VictoryLabel` altogether @karimkawambwa. I want the label component that can be used _everywhere_ `VictoryLabel` can.

**Comment by kilemensi** [comment]
>Am confused how this pie chart is rendered. It causes so many issues later such that I have to pass a manual radius, maybe we should allow for manual centre point to be passed aswell. The confusion stems from, why is there so much unused svg space and the pie looks so small. I don't really think the legend is moving it properly because it still gets cut off. The only reason it appears I believe is because we set overflow: visible:

1. Radius: That's the default behaviour of `VictoryPie`. If you don't specify `radius`, it tries to calculate: https://formidable.com/open-source/victory/docs/victory-pie/#radius
2. Origin: Yeah, you should be able to specify the center manually: https://formidable.com/open-source/victory/docs/victory-pie/#origin. If I've overriden it, I'll revert that option.

@karimkawambwa

**Comment by karimkawambwa** [comment]
> > Am confused how this pie chart is rendered. It causes so many issues later such that I have to pass a manual radius, maybe we should allow for manual centre point to be passed aswell. The confusion stems from, why is there so much unused svg space and the pie looks so small. I don't really think the legend is moving it properly because it still gets cut off. The only reason it appears I believe is because we set overflow: visible:
> 
> 1. Radius: That's the default behaviour of `VictoryPie`. If you don't specify `radius`, it tries to calculate: https://formidable.com/open-source/victory/docs/victory-pie/#radius
> 2. Origin: Yeah, you should be able to specify the center manually via `origin` prop: https://formidable.com/open-source/victory/docs/victory-pie/#origin. If I've overridden it, I'll revert that. `origin` should only be calculated if not specified.
> 
> @karimkawambwa

@kilemensi 

Yeah you definitely override it with no manual setting. But you do note that eh pie is so small, it takes up nothing close to the svg size. There is so much room left and not sure if the calculation is doing things right. The following in red is my expectation of the chart given the svg size and the legendWidth:

Screen Shot 2019-09-06 at 12 11 02 PM

**Comment by kilemensi** [comment]
> > > Am confused how this pie chart is rendered. It causes so many issues later such that I have to pass a manual radius, maybe we should allow for manual centre point to be passed aswell. The confusion stems from, why is there so much unused svg space and the pie looks so small. I don't really think the legend is moving it properly because it still gets cut off. The only reason it appears I believe is because we set overflow: visible:
> > 
> > 
> > 
> > 1. Radius: That's the default behaviour of `VictoryPie`. If you don't specify `radius`, it tries to calculate: https://formidable.com/open-source/victory/docs/victory-pie/#radius
> > 2. Origin: Yeah, you should be able to specify the center manually via `origin` prop: https://formidable.com/open-source/victory/docs/victory-pie/#origin. If I've overridden it, I'll revert that. `origin` should only be calculated if not specified.
> > 
> > @karimkawambwa
> 
> @kilemensi
> 
> Yeah you definitely override it with no manual setting. But you do note that eh pie is so small, it takes up nothing close to the svg size. There is so much room left and not sure if the calculation is doing things right. The following in red is my expectation of the chart given the svg size and the legendWidth:
> 
> Screen Shot 2019-09-06 at 12 11 02 PM

I'm reverting the origin issue @karimkawambwa but I believe the pie is small because of `padding`. Please check and let me know.

**Comment by kilemensi** [comment]
Included `origin` in the **Storybook** for manual positioning.

**Comment by karimkawambwa** [comment]
@kilemensi good note on the padding

**Pull request merged**
